name: E2E - Pepr Excellent Examples - IronBank AMD Image

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # 2AM EST/11PM PST

jobs:
  setup:
    name: controller image
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - name: Environment setup
        uses: ./.github/ironbank-actions/setup
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}

      - name: create matrix
        run: |
          matrix=$(
            node "$PEPR/.github/workflows/pepr-excellent-examples-matrix.js" "$PEPR_EXCELLENT_EXAMPLES_PATH"
          )
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"
        id: create-matrix

      - name: run e2e tests
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 6
          command: |
            cd "$PEPR_EXCELLENT_EXAMPLES_PATH"
            npm run --workspace=${{ matrix.name }} test:e2e -- \
              --image pepr:amd \
              --custom-package ../pepr-0.0.0-development.tgz

      - name: upload artifacts (troubleshooting)
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        if: always()
        with:
          name: "troubleshooting_logs_${{matrix.name}}"
          path: | 
            pepr-excellent-examples/package.json
            pepr-excellent-examples/package-lock.json
          if-no-files-found: error
          retention-days: 1

